### ISSUE TITLE
Errors in the list

### ISSUE THREAD

**Issue by d-mal** [enz/german-wordlist#2]
While looking through the words with unusual characters, I found a few that might be errors.

- Marineattachésés
It looks like Marineattaché and -s combined

- Zoïlus (and derivations)
https://de.wikipedia.org/wiki/Zoilos_von_Amphipolis
It's a person's proper name, but I doubt it's still used in a figurative way. If it were still common usage, I'd also include Sisiphos and Xanthippe.

**Comment by d-mal** [comment]
Hannovermesse
is a proper name and maybe a trademark. Probably the same as with
Viennale
Viennalen
Berlinale
Berlinalen

**Comment by enz** [comment]
Marineattachésés: typo, now fixed.
Zoïlus: looks like a proper noun, moved from words to blacklist.
Berlinale(n): regular noun according to the [Duden](https://www.duden.de/rechtschreibung/Berlinale).
Viennale(n), Hannovermesse: not listed in the Duden, but if Berlinale is a regular noun, I see no reason why these shouldn't be. Trademark doesn't mean that you are not allowed to use the word, but only that you are not allowed to use it as a name for another product in the same product category.
