### ISSUE TITLE
Terms for groups of people

### ISSUE THREAD

**Issue by d-mal** [enz/german-wordlist#3]
"Wayapopihíwi" (see https://de.wikipedia.org/wiki/Wayapopihíwi) is in the list. Is this really a German word? 

I'm using this as an example for names of small nations / ethnic groups.
People from larger nations and ethnic groups have "proper" German nouns: Franzosen, Engländer, Chinesen... and the corresponding adjectives französisch, englisch, chinesisch.

There is no other German word for the Wayapopihíwi people. But it looks a lot like German just borrowed the native word. If this counts as a "Lehnwort" already, then we probably have a few thousand other words missing in the list, as well as their adjectives and derivatives like Wayapopihíwisch, Wayapopihíwinerin?? 

If Wayapopihíwi does not fit in this list, where do you make the cut?

**Comment by d-mal** [comment]
Related: What to do with people from a city? 
```
Aachener
Aachenerin
Aachenerinnen
Aachenern
Aacheners
(...)
Zwickauer
Zwickauerin
Zwickauerinnen
Zwickauern
Zwickauers
```
Is there a rule which place is included? 
People from Peking and Moskau (even as Moskowiter) are included with all derivations, but only Washingtonerinnen from D.C. and nobody from New York ;-)

Maybe Wikipedia can help with lists:
https://de.wikipedia.org/wiki/Liste_der_größten_Metropolregionen_der_Welt
Tokyo is already a bit strange: We have 
```
Tokioer /-in /-innen /-n /-s
Tokioter /-n /-s
Tokyoter /-n /-s
```
So a few female versions could be added. 

https://de.wikipedia.org/wiki/Liste_der_größten_Städte_der_Europäischen_Union 
Bukarest is the largest with incomplete support in the list: only "Bukaresterinnen" are included.

https://de.wikipedia.org/wiki/Liste_der_Groß-_und_Mittelstädte_in_Deutschland
Mönchengladbach is the first that's missing.

Xanten has only 22000 inhabitants, but Xantener / Xantenern / Xanteners and Xantens(?) are on the list. I guess it has historical importance - and it starts with X ;*)

**Comment by enz** [comment]
I would say if the German Wikipedia uses Wayapopihíwi as a lemma for the article then it is a German word because the Wikipedia naming conventions require to use the spelling most commonly used in German texts as a lemma. The [German Wiktionary](https://de.wiktionary.org/wiki/Wayapopih%C3%ADwi) also lists the word as a regular noun.

Toponyms are proper nouns and not allowed by the Scrabble rules, but nouns and adjectives derived from toponyms are allowed. You can find more information in the official German Scrabble rules linked from the [Wiki](https://github.com/enz/german-wordlist/wiki) of this project.

**Comment by enz** [comment]
If I interpret the German Scrabble rules correctly, the rule for which nouns and adjectives derived from places to include is whether the place is a country or a city, no matter what the  number of inhabitants is.

**Comment by d-mal** [comment]
Thanks, cool -- so there are a whole lot of words that can be added to the list :)
I guess there must be some automatic way to use Wikipedia categories or lists to scrape a lot more placenames... but adding the standard endings may produce errors in some special cases. Maybe a safer way would be to do it slowly and manually. Maybe if I get bored in the next few months I'll do a list with all the countries first.
